import { h, Fragment } from "/js/runtime/dom.js";
import { motion } from "/js/runtime/motion.js";
import { Truck, RotateCcw, ArrowRight } from "/js/runtime/icons.js";
import Link from "/js/runtime/navigation.js";
export default function ShippingReturnsPage() {
    return (h("div", { className: "flex-1 w-full min-h-screen bg-[#FAFAFA] pb-24" },
        h("div", { className: "w-full bg-[#0B0B0B] text-white pt-24 pb-20 px-6 md:px-12 flex flex-col items-center text-center relative overflow-hidden" },
            h("div", { className: "absolute top-[-20%] right-[-10%] w-[50vw] h-[50vw] bg-[#A6532A]/10 rounded-full blur-[120px] pointer-events-none" }),
            h("div", { className: "w-full max-w-[1400px] mx-auto relative z-10 flex flex-col items-center" },
                h("p", { className: "text-[9px] font-bold tracking-[0.35em] text-[#A6532A] uppercase mb-4" }, "CUSTOMER CARE"),
                h("h1", { className: "text-4xl md:text-6xl font-black tracking-tighter text-white mb-6 uppercase", style: { fontFamily: "var(--font-syncopate)" } }, "SHIPPING & RETURNS"),
                h("p", { className: "text-gray-400 max-w-xl text-xs md:text-sm leading-relaxed font-medium" }, "This is a collection preview. No physical orders are placed, shipped, or returned."))),
        h("div", { className: "w-full max-w-[1000px] mx-auto px-6 mt-16 grid grid-cols-1 md:grid-cols-2 gap-12" },
            h(motion.div, { initial: { opacity: 0, x: -30 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.6, ease: "easeOut" }, className: "bg-white rounded-[32px] p-8 md:p-12 border border-gray-100 shadow-sm flex flex-col" },
                h("div", { className: "w-12 h-12 rounded-2xl bg-[#A6532A]/10 text-[#A6532A] flex items-center justify-center mb-8" },
                    h(Truck, { size: 20 })),
                h("h2", { className: "text-2xl font-black text-[#0B0B0B] tracking-tight uppercase mb-6", style: { fontFamily: "var(--font-syncopate)" } }, "Fulfillment & Delivery"),
                h("div", { className: "flex flex-col gap-6 text-xs md:text-sm text-gray-500 font-medium leading-relaxed" },
                    h("div", null,
                        h("p", { className: "font-bold text-[#0B0B0B] uppercase tracking-wider mb-2" }, "Collection Preview"),
                        h("p", null, "This demo does not accept orders or dispatch physical products. Explore the catalog and try building a collection bag.")),
                    h("div", null,
                        h("p", { className: "font-bold text-[#0B0B0B] uppercase tracking-wider mb-2" }, "Demo Pricing"),
                        h("p", null, "All prices and stock counts are sample product details. No shipping charge is collected.")),
                    h("div", null,
                        h("p", { className: "font-bold text-[#0B0B0B] uppercase tracking-wider mb-2" }, "Browse Anywhere"),
                        h("p", null, "The collection can be browsed from anywhere. There are no delivery estimates or tracking services in this demo.")))),
            h(motion.div, { initial: { opacity: 0, x: 30 }, animate: { opacity: 1, x: 0 }, transition: { duration: 0.6, ease: "easeOut" }, className: "bg-white rounded-[32px] p-8 md:p-12 border border-gray-100 shadow-sm flex flex-col" },
                h("div", { className: "w-12 h-12 rounded-2xl bg-[#A6532A]/10 text-[#A6532A] flex items-center justify-center mb-8" },
                    h(RotateCcw, { size: 20 })),
                h("h2", { className: "text-2xl font-black text-[#0B0B0B] tracking-tight uppercase mb-6", style: { fontFamily: "var(--font-syncopate)" } }, "Exchanges & Returns"),
                h("div", { className: "flex flex-col gap-6 text-xs md:text-sm text-gray-500 font-medium leading-relaxed" },
                    h("div", null,
                        h("p", { className: "font-bold text-[#0B0B0B] uppercase tracking-wider mb-2" }, "No Purchases"),
                        h("p", null, "No purchases take place here, so there are no physical returns or exchanges to arrange.")),
                    h("div", null,
                        h("p", { className: "font-bold text-[#0B0B0B] uppercase tracking-wider mb-2" }, "Find Your Fit"),
                        h("p", null, "Compare the garment measurements in each product size guide. Choose a size to see how the bag interaction works.")),
                    h("div", null,
                        h("p", { className: "font-bold text-[#0B0B0B] uppercase tracking-wider mb-2" }, "Try Your Rotation"),
                        h("p", null, "Remove a piece from your bag, change its quantity, or try another size at any time during your visit."))))),
        h("div", { className: "w-full max-w-[1000px] mx-auto px-6 mt-16" },
            h("div", { className: "bg-[#0B0B0B] rounded-[32px] p-8 md:p-12 text-white relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-8 shadow-2xl" },
                h("div", { className: "absolute top-0 right-0 w-[30vw] h-[30vw] bg-[#A6532A]/10 rounded-full blur-[80px] pointer-events-none" }),
                h("div", { className: "relative z-10 flex-1" },
                    h("h3", { className: "text-xl md:text-2xl font-black tracking-tight uppercase mb-3", style: { fontFamily: "var(--font-syncopate)" } }, "Exploring Your Fit?"),
                    h("p", { className: "text-xs text-gray-400 font-medium max-w-md leading-relaxed" }, "Visit the product size guides or explore the contact form preview to see the complete demo experience.")),
                h(Link, { href: "/contact-us", className: "relative z-10 bg-white hover:bg-[#A6532A] text-[#0B0B0B] hover:text-white px-8 py-4 rounded-full text-[10px] font-bold tracking-[0.25em] uppercase transition-colors shrink-0 flex items-center gap-2 shadow-xl hover:scale-105" },
                    "CONTACT SUPPORT ",
                    h(ArrowRight, { size: 14 }))))));
}
