import { h, Fragment } from "/js/runtime/dom.js";
import { motion } from "/js/runtime/motion.js";
export default function MaterialSystem() {
    return (h("section", { className: "w-full text-white py-12 md:py-24 relative overflow-hidden flex flex-col justify-between bg-cover bg-center", style: { backgroundImage: "url('/images/streetwear/street-fabric.png')" } },
        h("div", { className: "absolute top-1/2 -translate-y-1/2 right-[-5%] md:right-0 w-[75%] md:w-[60%] h-[60%] md:h-full z-0 opacity-40 md:opacity-90 [mask-image:linear-gradient(to_right,transparent_10%,black_70%)] md:[mask-image:linear-gradient(to_right,transparent,black_40%)] pointer-events-none flex justify-end items-center" },
            
            h("div", { className: "absolute inset-0 bg-gradient-to-r from-transparent to-transparent" })),
        h("div", { className: "max-w-[1600px] mx-auto px-6 md:px-12 lg:px-20 w-full relative z-10 flex flex-col h-full" },
            h("div", { className: "mb-12 md:mb-20" },
                h(motion.div, { initial: { opacity: 0, y: 10 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, className: "flex items-center gap-3 mb-6" },
                    h("span", { className: "text-[10px] md:text-xs font-bold tracking-[0.3em] text-white/70 uppercase" }, "MURHOPRINTS MATERIAL SYSTEM / 002")),
                h(motion.h2, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: 0.1 }, className: "text-5xl md:text-[70px] lg:text-[100px] font-medium tracking-tighter uppercase leading-[0.85]", style: { fontFamily: "var(--font-syncopate)" } },
                    "PRINT.",
                    h("br", null),
                    "FIT.",
                    h("br", null),
                    "REPEAT.")),
            h("div", { className: "w-full mb-12 md:mb-16" },
                h("div", { className: "w-full h-[1px] bg-white/20 mb-8" }),
                h("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8 md:gap-6" },
                    h(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: 0.2 }, className: "flex flex-col" },
                        h("span", { className: "text-[10px] font-medium text-white/50 mb-3" }, "01"),
                        h("h3", { className: "text-lg md:text-xl font-bold tracking-wider uppercase mb-1" }, "HEAVY COTTON"),
                        h("p", { className: "text-[9px] font-bold tracking-[0.1em] text-white/70 uppercase mb-3" }, "240 GSM JERSEY"),
                        h("p", { className: "text-[11px] text-white/60 mb-6 md:mb-8 max-w-[180px] leading-relaxed" }, "Substantial cotton. Soft everyday feel."),
                        h("div", { className: "text-[50px] md:text-[80px] font-light tracking-tighter text-white/30 leading-none mb-3 md:mb-4" }, "240"),
                        h("p", { className: "text-[9px] font-bold tracking-[0.15em] text-white/50 uppercase" }, "WEIGHTY FEEL / EASY DRAPE")),
                    h(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: 0.3 }, className: "flex flex-col" },
                        h("span", { className: "text-[10px] font-medium text-white/50 mb-3" }, "02"),
                        h("h3", { className: "text-lg md:text-xl font-bold tracking-wider uppercase mb-1" }, "ORIGINAL PRINTS"),
                        h("p", { className: "text-[9px] font-bold tracking-[0.1em] text-white/70 uppercase mb-3" }, "GRAPHICS WITH CHARACTER"),
                        h("p", { className: "text-[11px] text-white/60 mb-6 md:mb-8 max-w-[180px] leading-relaxed" }, "Artwork that makes a simple fit your own."),
                        h("div", { className: "text-[50px] md:text-[80px] font-light tracking-tighter text-white/30 leading-none mb-3 md:mb-4" }, "INK"),
                        h("p", { className: "text-[9px] font-bold tracking-[0.15em] text-white/50 uppercase" }, "BOLD COLOUR / CLEAN DETAIL")),
                    h(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: 0.4 }, className: "flex flex-col" },
                        h("span", { className: "text-[10px] font-medium text-white/50 mb-3" }, "03"),
                        h("h3", { className: "text-lg md:text-xl font-bold tracking-wider uppercase mb-1" }, "RELAXED FIT"),
                        h("p", { className: "text-[9px] font-bold tracking-[0.1em] text-white/70 uppercase mb-3" }, "ROOM TO BE YOURSELF"),
                        h("p", { className: "text-[11px] text-white/60 mb-6 md:mb-8 max-w-[180px] leading-relaxed" }, "Boxy tees. Wide legs. Effortless layers."),
                        h("div", { className: "text-[50px] md:text-[80px] font-light tracking-tighter text-white/30 leading-none mb-3 md:mb-4" }, "XL"),
                        h("p", { className: "text-[9px] font-bold tracking-[0.15em] text-white/50 uppercase" }, "DROPPED SHOULDERS / EASY VOLUME")))),
            h(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, transition: { delay: 0.5 }, className: "w-full flex flex-col items-center justify-center text-center pt-8 border-t border-white/20" },
                h("h4", { className: "text-base md:text-lg font-medium tracking-wide mb-2 text-white/90" }, "YOUR PRINT. YOUR FIT. YOUR EVERYDAY."),
                h("p", { className: "text-xs text-white/60" }, "Wear it your way.")))));
}
